import type { Player } from "../types/players.types";

export const players: Player[] = [
    { name: "Deacon Abela", shortName: "Deacon", number: 5, password: "DA5", role: ["USER"], personRole: "player" },
    { name: "Gabriel Bohrer Mentz", shortName: "Mentz", number: 3, password: "GBM3", role: ["ADMIN"], personRole: "player"},
    { name: "Andy Borg", shortName: "Andy", number: 6, password: "AB6", role: ["USER"], personRole: "player" },
    { name: "Marc van de Bovenkamp", shortName: "Marc", number: 22, role: ["USER"], personRole: "player" },
    { name: "Pablo Fonseca", shortName: "Pablo", number: 4, role: ["USER"], personRole: "player" },
    { name: "Lennon Thompson", shortName: "Lennon", number: 2, role: ["USER"], personRole: "player" },
    { name: "Clayton Failla", shortName: "Clayton", number: 13, role: ["USER"], personRole: "player" },
    { name: "Luis Carlos Riascos", shortName: "Luis", number: 14, role: ["USER"], personRole: "player" },
    { name: "Jork Becerra", shortName: "Jork", number: 18, role: ["USER"], personRole: "player" },
    { name: "David Xuereb", shortName: "David", number: 30, role: ["USER"], personRole: "player" },
    { name: "Kevin Tulimieri", shortName: "Tuli", number: 92, role: ["USER"], personRole: "player" },
    { name: "Brooklyn Borg", shortName: "Broo", number: 8, role: ["USER"], personRole: "player" },
    { name: "Santiago Martinez", shortName: "Santi", number: 7, role: ["USER"], personRole: "player" },
    { name: "Johan Bonilla", shortName: "Johan", number: 57, role: ["USER"], personRole: "player" },
    { name: "Andre Carlos", shortName: "Andre", number: 9, role: ["USER"], personRole: "player" },
    { name: "Maxuell Maia", shortName: "Samu", number: 10, role: ["USER"], personRole: "player" },
    { name: "Fabrico Kante", shortName: "Kante", number: 98, role: ["USER"], personRole: "player" },
    { name: "Mathias Conti", shortName: "Conti", number: 29, role: ["USER"], personRole: "player" },
    { name: "Sanghyon Roh", shortName: "Sang", number: 24, role: ["USER"], personRole: "player" },
    { name: "Ayrton Dimech", shortName: "Ayrton", number: 23, role: ["USER"], personRole: "player" },
    { name: "Karl Sargent", shortName: "Karl", number: 1, role: ["USER"], personRole: "player" },
    { name: "Alesk Lubik", shortName: "Alesk", number: 70, role: ["USER"], personRole: "player" },
    { name: "Kristen Galea", shortName: "Kisten", number: 20, role: ["USER"], personRole: "player" },
    { name: "Mark Abela", shortName: "Mark", number: 0, password: "MAPC", role: ["MODERATOR"], personRole: "coach"},
    { name: "Clive Mizzi", shortName: "Clive", number: 0, password: "CMFC", role: ["MODERATOR"], personRole: "coach"},
    { name: "Matthew Mizzi", shortName: "Matthew", number: 0, password: "MMSC", role: ["MODERATOR"], personRole: "coach"}
]