import type { Player } from "../types/players.types";

export const players: Player[] = [
    { name: "Deacon Abela", number: 5, password: "DA5", role: ["user"], personRole: "player" },
    { name: "Gabriel Bohrer Mentz", number: 3, password: "GBM3", role: ["admin"], personRole: "player"},
    { name: "Andy Borg", number: 6, password: "AB6", role: ["user"], personRole: "player" },
    { name: "Marc van de Bovenkamp", number: 22, role: ["user"], personRole: "player" },
    { name: "Pablo Fonseca", number: 4, role: ["user"], personRole: "player" },
    { name: "Lennon Thompson", number: 2, role: ["user"], personRole: "player" },
    { name: "Clayton Failla", number: 13, role: ["user"], personRole: "player" },
    { name: "Luis Carlos Riascos", number: 14, role: ["user"], personRole: "player" },
    { name: "Jork Becerra", number: 18, role: ["user"], personRole: "player" },
    { name: "David Xuereb", number: 30, role: ["user"], personRole: "player" },
    { name: "Kevin Tulimieri", number: 92, role: ["user"], personRole: "player" },
    { name: "Brooklyn Borg", number: 8, role: ["user"], personRole: "player" },
    { name: "Santiago Martinez", number: 7, role: ["user"], personRole: "player" },
    { name: "Johan Bonilla", number: 57, role: ["user"], personRole: "player" },
    { name: "Andre Carlos", number: 9, role: ["user"], personRole: "player" },
    { name: "Maxuell Maia", number: 10, role: ["user"], personRole: "player" },
    { name: "Fabrico Kante", number: 98, role: ["user"], personRole: "player" },
    { name: "Mathias Conti", number: 29, role: ["user"], personRole: "player" },
    { name: "Sanghyon Roh", number: 24, role: ["user"], personRole: "player" },
    { name: "Ayrton Dimech", number: 23, role: ["user"], personRole: "player" },
    { name: "Karl Sargent", number: 1, role: ["user"], personRole: "player" },
    { name: "Alesk Lubik", number: 70, role: ["user"], personRole: "player" },
    { name: "Kristen Galea", number: 20, role: ["user"], personRole: "player" },
    { name: "Mark Abela", number: 0, password: "MAPC", role: ["admin"], personRole: "coach"},
    { name: "Clive Mizzi", number: 0, password: "CMFC", role: ["admin"], personRole: "coach"},
    { name: "Matthew Mizzi", number: 0, password: "MMSC", role: ["admin"], personRole: "coach"}
]